import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/helper/ShadcnProvider";
import { AuthProvider } from "@/helper/NextAuthProvider";
import { Header } from "@/components/header";
import { HeaderDock } from "@/components/Dock";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-2 h-[100vh]">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <header>
              <Header />
            </header>
            {children}
            <footer className="absolute bottom-1 left-0 right-0">
              <HeaderDock />
            </footer>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
